version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/ts-backend-boilerplate

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install the Dependencies
          command: |
            sudo apt-get install rsync
            yarn bootstrap

      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: Lint the Application
          command: yarn lint

      - run:
          name: Build the Application
          command: yarn compile

      - run:
          name: Run the unit tests
          command: yarn test

      - run:
          name: Collect Unit Test Reports
          command: |
            mkdir -p ~/test-results/jest
            mkdir -p ~/artifacts/jest
            cp junit.xml ~/test-results/jest/unit-test-results.xml
            cp -r coverage ~/artifacts/jest/
          when: always

      - store_test_results:
          path: ~/test-results
          when: always

      - store_artifacts:
          path: ~/artifacts
          when: always

      - run:
          name: Build the Docker Image
          command: |
            docker build .
